"""
=========================================================================
DADOS DE INTELIGÊNCIA GEOESPACIAL - PEDREIRAS E MINERAÇÕES
=========================================================================
Fonte: Relatório Exaustivo de Inteligência Geoespacial e Infraestrutura
Logística de Agregados Minerais (2019-2026).

Cada entrada contém:
  - nome          : nome principal da pedreira/mineração
  - procedencias  : lista de substrings para match com campo 'procedencia'
                    dos projetos CAUQ (busca case-insensitive)
  - localizacao   : município e estado de referência
  - natureza      : litologia principal (BASALTO, GRANITO, etc.)
  - endereco      : endereço físico ou referência rodoviária
  - lat / lon     : coordenadas geográficas decimais (SIRGAS 2000)
  - estado        : sigla UF
=========================================================================
"""

PEDREIRAS_INTEL = [
    # ── TREVO ──────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA TREVO - CASCAVEL",
        "procedencias": ["TREVO CASCAVEL", "PEDREIRA TREVO", "PEDREIRAS TREVO", "TREVO"],
        "localizacao": "CASCAVEL - PR",
        "natureza": "BASALTO",
        "endereco": "Rua Carlos Gomes, 1406/1448 e Rua Gandhi S/N Lote 67, Cascavel - PR",
        "lat": -24.959,
        "lon": -53.459,
        "estado": "PR",
    },
    {
        "nome": "PEDREIRA TREVO - TERRA ROXA",
        "procedencias": ["TREVO TERRA ROXA", "TREVO TERRA"],
        "localizacao": "TERRA ROXA - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-163, Km 316, Serra do Maracaju, Terra Roxa - PR",
        "lat": -24.162,
        "lon": -53.754,
        "estado": "PR",
    },
    {
        "nome": "PEDREIRA TREVO - SANTA TEREZA DO OESTE",
        "procedencias": ["TREVO STª MARIA", "TREVO STA MARIA", "TREVO SANTA MARIA", "TREVO SANTA TEREZA", "PEDREIRA SANTA MARIA"],
        "localizacao": "SANTA TEREZA DO OESTE - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-163, KM 184, S/N, Santa Tereza do Oeste - PR",
        "lat": -24.798,
        "lon": -53.218,
        "estado": "PR",
    },
    # ── DELLAI ─────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DELLAI - TOMAZINA",
        "procedencias": ["DELLAI PITANGA", "DELLAI TOMAZINA", "DELLAI"],
        "localizacao": "TOMAZINA - PR",
        "natureza": "BASALTO",
        "endereco": "Fazenda Cristalina, S/N - Pedreira, Tomazina - PR (CEP 84935-000)",
        "lat": -23.736,
        "lon": -49.955,
        "estado": "PR",
    },
    {
        "nome": "PEDREIRA DELLAI - SIQUEIRA CAMPOS",
        "procedencias": ["DELLAI SIQUEIRA", "DELLAI SIQUEIRA CAMPOS"],
        "localizacao": "SIQUEIRA CAMPOS - PR",
        "natureza": "BASALTO",
        "endereco": "Rua Angelina Geralda de Jesus, 875, Sala 1, Centro, Siqueira Campos - PR",
        "lat": -23.688,
        "lon": -49.833,
        "estado": "PR",
    },
    # ── BRITAPLAN / COXILHA RICA ────────────────────────────────────────────
    {
        "nome": "PEDREIRA BRITAPLAN",
        "procedencias": ["BRITAPLAN"],
        "localizacao": "LAGES - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-116, S/Nº, Km 253, Lages - SC (CEP 88517-600)",
        "lat": -27.815,
        "lon": -50.326,
        "estado": "SC",
    },
    {
        "nome": "PEDREIRA COXILHA RICA",
        "procedencias": ["COXILHA RICA", "COXILHA"],
        "localizacao": "LAGES - SC",
        "natureza": "DACITO",
        "endereco": "Acesso via SC-390, a 42 km do centro de Lages - SC",
        "lat": -27.972,
        "lon": -50.728,
        "estado": "SC",
    },
    # ── DALBA ──────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DALBA - FRANCISCO BELTRÃO",
        "procedencias": ["DALBA FC°", "DALBA FRANCISCO", "DALBA BELTRÃO", "DALBA BELTRAO"],
        "localizacao": "FRANCISCO BELTRÃO - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia PR-566, Km 5,5, S/N, Secção São Miguel, Francisco Beltrão - PR",
        "lat": -26.133,
        "lon": -53.082,
        "estado": "PR",
    },
    {
        "nome": "PEDREIRA DALBA - GUARAPUAVA",
        "procedencias": ["DALBA GUARAPUAVA", "DALBAGUARAPUAVA", "DALBA"],
        "localizacao": "GUARAPUAVA - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia PR-170, Km 7,5 - Saída para o Pinhão, Guarapuava - PR",
        "lat": -25.426,
        "lon": -51.522,
        "estado": "PR",
    },
    # ── IBAITI ─────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA IBAITI",
        "procedencias": ["IBAITI", "PED. IBAITI", "PEDREIRA IBAITI"],
        "localizacao": "IBAITI - PR",
        "natureza": "BASALTO",
        "endereco": "Ibaiti - PR | UTM: N 7.362.245 / E 582.687 (SIRGAS 2000)",
        "lat": -23.839518,
        "lon": -50.184718,
        "estado": "PR",
    },
    # ── ICA / COMPASA ──────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ICA",
        "procedencias": ["PEDREIRA ICA", "ICA IBIPORÃ", "ICA IBIPORA", "ICA"],
        "localizacao": "IBIPORÃ - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia PR-862 (Contorno Norte de Ibiporã), KM 9, Ibiporã - PR",
        "lat": -23.271,
        "lon": -51.046,
        "estado": "PR",
    },
    {
        "nome": "PEDREIRA COMPASA - IBIPORÃ",
        "procedencias": ["COMPASA IBIPORÃ", "COMPASA IBIPORA", "COMPASA"],
        "localizacao": "IBIPORÃ - PR",
        "natureza": "BASALTO / AREIA",
        "endereco": "Malha logística PR-862 / Rio Tibagi, Ibiporã - PR",
        "lat": -23.273,
        "lon": -51.060,
        "estado": "PR",
    },
    # ── SAMP ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA SAMP",
        "procedencias": ["PEDREIRA SAMP", "SAMPSÃO MIGUEL", "SAMP"],
        "localizacao": "SÃO MIGUEL DO IGUAÇU - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-277, KM 687, Serra do Mico, São Miguel do Iguaçu - PR",
        "lat": -25.404,
        "lon": -54.253,
        "estado": "PR",
    },
    # ── GUARICANA ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA GUARICANA",
        "procedencias": ["GUARICANA"],
        "localizacao": "SÃO JOSÉ DOS PINHAIS - PR",
        "natureza": "RIOLITO / GRANITO",
        "endereco": "Estrada Velha Da Guaricana, 200, São José dos Pinhais - PR",
        "lat": -25.582,
        "lon": -49.093,
        "estado": "PR",
    },
    # ── TUPY ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA TUPY",
        "procedencias": ["PEDREIRA TUPY", "TUPY"],
        "localizacao": "IBIPORÃ / LONDRINA - PR",
        "natureza": "BASALTO",
        "endereco": "Proximidades de Ibiporã - PR",
        "lat": -23.270,
        "lon": -51.050,
        "estado": "PR",
    },
    # ── UBIRATÃ ────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA UBIRATÃ",
        "procedencias": ["UBIRATÃ", "UBIRATA"],
        "localizacao": "UBIRATÃ - PR",
        "natureza": "BASALTO",
        "endereco": "Ubiratã - PR (SIRGAS 2000: Lat -24.54, Lon -52.99)",
        "lat": -24.540,
        "lon": -52.990,
        "estado": "PR",
    },
    # ── KERBER ─────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA KERBER - PORTO UNIÃO",
        "procedencias": ["KERBER PORTO UNIÃO", "KERBER PORTO UNIAO", "KERBER"],
        "localizacao": "PORTO UNIÃO - SC",
        "natureza": "BASALTO",
        "endereco": "Porto União - SC (Coordenadas: -26.217424, -51.126636)",
        "lat": -26.217424,
        "lon": -51.126636,
        "estado": "SC",
    },
    {
        "nome": "PEDREIRA KERBER - TRÊS BARRAS",
        "procedencias": ["KERBER TRÊS BARRAS", "KERBER TRES BARRAS", "KERBER BITURUNA", "CPV + TRÊS BARRAS", "MINERAÇÃO CPV"],
        "localizacao": "TRÊS BARRAS - SC",
        "natureza": "BASALTO",
        "endereco": "Malha viária de Três Barras / São Mateus do Sul - SC",
        "lat": -26.116,
        "lon": -50.316,
        "estado": "SC",
    },
    # ── DALMINA ────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DALMINA - MARECHAL CÂNDIDO RONDON",
        "procedencias": ["DALMINA M.C.R", "DALMINA RONDON", "DALMINA"],
        "localizacao": "MARECHAL CÂNDIDO RONDON - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-163, KM 290,5, Marechal Cândido Rondon - PR",
        "lat": -24.557,
        "lon": -54.052,
        "estado": "PR",
    },
    # ── MARC ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA MARC / BASALTO COSTA",
        "procedencias": ["MARC", "BASALTO COSTA", "PEDREIRAS MARC"],
        "localizacao": "SÃO JOSÉ DOS PINHAIS - PR",
        "natureza": "GRANITO E BASALTO",
        "endereco": "Rodovia BR-376, Nº 14.578, Bairro Itália, São José dos Pinhais - PR",
        "lat": -25.610,
        "lon": -49.205,
        "estado": "PR",
    },
    # ── SETEP / SBM ────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA SETEP / SBM - MARACAJÁ",
        "procedencias": ["SETEP", "SBM", "CBM"],
        "localizacao": "MARACAJÁ - SC",
        "natureza": "BASALTO / GRANITO",
        "endereco": "Rua Pedro Rocha, S/N, Maracajá - SC | Matriz: R. Francisco Martinhago, 258, Criciúma - SC",
        "lat": -28.831,
        "lon": -49.462,
        "estado": "SC",
    },
    # ── BARRACÃO (ITAJAÍ) ──────────────────────────────────────────────────
    {
        "nome": "PEDREIRA BARRACÃO",
        "procedencias": ["BARRACÃO", "BARRACAO"],
        "localizacao": "ITAJAÍ - SC",
        "natureza": "GRANITO",
        "endereco": "Bacia do Rio Itajaí-Açu, Itajaí - SC (Lat 26°55'08\"S, Lon 49°03'57\"O)",
        "lat": -26.918889,
        "lon": -49.065833,
        "estado": "SC",
    },
    # ── COMPENSA ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA COMPENSA",
        "procedencias": ["COMPENSA"],
        "localizacao": "PAULA FREITAS - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-476, KM 347, Colônia Azul, Paula Freitas - PR",
        "lat": -26.155,
        "lon": -52.699,
        "estado": "PR",
    },
    # ── RIO QUATI ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA RIO QUATI",
        "procedencias": ["RIO QUATI", "QUATI"],
        "localizacao": "CASCAVEL - PR",
        "natureza": "BASALTO",
        "endereco": "Rua Rio da Paz, KM 4, Cascavel - PR",
        "lat": -24.970,
        "lon": -53.482,
        "estado": "PR",
    },
    # ── ÁGUA AMARELA ───────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ÁGUA AMARELA",
        "procedencias": ["ÁGUA AMARELA", "AGUA AMARELA"],
        "localizacao": "LAPA - PR",
        "natureza": "BASALTO",
        "endereco": "Polo limítrofe Campo do Tenente / Lapa - PR",
        "lat": -25.770,
        "lon": -49.719,
        "estado": "PR",
    },
    # ── DALL ROSS ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DALL ROSS",
        "procedencias": ["DALL ROSS", "DAL ROSS", "DALL"],
        "localizacao": "VITORINO / PATO BRANCO - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-158, Km 547, Zona Rural, Vitorino - PR",
        "lat": -26.002,
        "lon": -52.730,
        "estado": "PR",
    },
    # ── MORO ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA MORO",
        "procedencias": ["PEDREIRA MORO", "MORO"],
        "localizacao": "PONTA GROSSA - PR",
        "natureza": "BASALTO",
        "endereco": "Acesso à Rodovia BR-376, perímetro industrial de Ponta Grossa - PR",
        "lat": -25.094,
        "lon": -50.163,
        "estado": "PR",
    },
    # ── EXPRESSA ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA EXPRESSA",
        "procedencias": ["EXPRESSA", "PEDREIRA EXPRESSA"],
        "localizacao": "LONDRINA - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia Celso Garcia Cid (PR-445), KM 364, Londrina - PR",
        "lat": -23.302,
        "lon": -51.175,
        "estado": "PR",
    },
    # ── PEDRA NORTE ────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA PEDRA NORTE",
        "procedencias": ["PEDRA NORTE"],
        "localizacao": "CORNÉLIO PROCÓPIO - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia PR-160, S/N, Km 3,5, Cornélio Procópio - PR",
        "lat": -23.179,
        "lon": -50.649,
        "estado": "PR",
    },
    # ── CASTILHO ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CASTILHO",
        "procedencias": ["CASTILHO"],
        "localizacao": "RIBEIRÃO CLARO - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia RM-100, KM 2,2, Estrada dos Baggios, Ribeirão Claro - PR",
        "lat": -23.107,
        "lon": -49.759,
        "estado": "PR",
    },
    # ── USINA NORTE ────────────────────────────────────────────────────────
    {
        "nome": "USINA NORTE",
        "procedencias": ["USINA NORTE"],
        "localizacao": "CURITIBA - PR",
        "natureza": "GRANITO",
        "endereco": "Rua Wilson Gomes Ramos, 5, Bairro Abranches, Curitiba - PR",
        "lat": -25.375,
        "lon": -49.276,
        "estado": "PR",
    },
    # ── BOSCARDIN ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA BOSCARDIN",
        "procedencias": ["BOSCARDIN"],
        "localizacao": "PIRAQUARA - PR",
        "natureza": "BASALTO",
        "endereco": "Rua dos Miosótis, 43, Recreio da Serra, Piraquara - PR",
        "lat": -25.454,
        "lon": -49.072,
        "estado": "PR",
    },
    # ── GASPAR IOMERÊ ──────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA GASPAR - IOMERÊ",
        "procedencias": ["GASPAR IOMERÊ", "GASPAR IOMERE", "GASPAR"],
        "localizacao": "IOMERÊ - SC",
        "natureza": "BASALTO",
        "endereco": "Estrada Geral Iomerê/Treze Tílias, KM 02, Iomerê - SC",
        "lat": -26.975,
        "lon": -51.244,
        "estado": "SC",
    },
    # ── ZANCANARO ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ZANCANARO",
        "procedencias": ["ZANCANARO"],
        "localizacao": "CORONEL VIVIDA - PR",
        "natureza": "BASALTO",
        "endereco": "Coronel Vivida - PR (26°14'20.29\"S, 52°41'54.56\"W)",
        "lat": -26.238969,
        "lon": -52.698489,
        "estado": "PR",
    },
    # ── VALE DAS PEDRAS ────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA VALE DAS PEDRAS",
        "procedencias": ["VALE DAS PEDRAS"],
        "localizacao": "QUATRO BARRAS - PR",
        "natureza": "GRANITO",
        "endereco": "Sítio Ilha do Sapo, S/N, Quatro Barras - PR",
        "lat": -25.369,
        "lon": -49.074,
        "estado": "PR",
    },
    # ── SANTIAGO ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA SANTIAGO",
        "procedencias": ["PEDREIRA SANTIAGO", "SANTIAGO"],
        "localizacao": "CHOPINZINHO - PR",
        "natureza": "BASALTO",
        "endereco": "Rua 13 de Maio, S/N, Bairro São Miguel, Chopinzinho - PR",
        "lat": -25.860372,
        "lon": -52.517261,
        "estado": "PR",
    },
    # ── REMANSO ────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA REMANSO",
        "procedencias": ["REMANSO"],
        "localizacao": "PATO BRANCO - PR",
        "natureza": "BASALTO",
        "endereco": "Estrada Vicinal São Braz, KM 02, Cidade Industrial, Pato Branco - PR",
        "lat": -26.228,
        "lon": -52.671,
        "estado": "PR",
    },
    # ── AGRO ROQUE ─────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA AGRO ROQUE",
        "procedencias": ["AGRO ROQUE", "PEDREIRA IMBAÚ", "PEDREIRA IMBAÚ RESERVA", "PEDREIRA 02 (IMBAÚ)", "PEDREIRA IMBAÚ RESERVA", "IMBAÚ"],
        "localizacao": "IMBAÚ - PR",
        "natureza": "DIABÁSIO",
        "endereco": "Proximidades do pedágio Imbaú/Ortigueira, Imbaú - PR",
        "lat": -24.459,
        "lon": -50.773,
        "estado": "PR",
    },
    # ── INFRASUL ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA INFRASUL",
        "procedencias": ["INFRASUL"],
        "localizacao": "JOINVILLE - SC",
        "natureza": "GNAISSE",
        "endereco": "Rodovia Rio Zoada (Joinville - Jaraguá do Sul) | Escritório: R. Gothard Kaesemodel, 254, Joinville - SC",
        "lat": -26.304,
        "lon": -48.846,
        "estado": "SC",
    },
    # ── TCE ────────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA TCE",
        "procedencias": ["PEDREIRA TCE", "TCE"],
        "localizacao": "CURITIBA - PARANAGUÁ - PR",
        "natureza": "BASALTO",
        "endereco": "Faixa de domínio da Estrada de Ferro Curitiba-Paranaguá (UTM 707527.14)",
        "lat": -25.519,
        "lon": -49.166,
        "estado": "PR",
    },
    # ── CEGE ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CEGE",
        "procedencias": ["PEDREIRA CEGE", "CEGE"],
        "localizacao": "CASCAVEL - PR",
        "natureza": "BASALTO",
        "endereco": "Cascavel - PR (UTM N 7.071.585 / E 404.000, SIRGAS 2000)",
        "lat": -24.940,
        "lon": -53.486,
        "estado": "PR",
    },
    # ── MINERAÇÃO KAROLINE ─────────────────────────────────────────────────
    {
        "nome": "MINERAÇÃO KAROLINE",
        "procedencias": ["KAROLINE"],
        "localizacao": "RIO DAS ANTAS - SC",
        "natureza": "BASALTO",
        "endereco": "Estrada Linha Rio Bonito, S/N, Zona Rural, Rio das Antas - SC",
        "lat": -26.899,
        "lon": -51.079,
        "estado": "SC",
    },
    # ── MINERAÇÃO BARALDI ──────────────────────────────────────────────────
    {
        "nome": "MINERAÇÃO BARALDI",
        "procedencias": ["BARALDI"],
        "localizacao": "ALTO PARAÍSO - PR",
        "natureza": "AREIA",
        "endereco": "Lotes 85 e 86, Gleba 8, Porto Figueira, Alto Paraíso - PR",
        "lat": -23.537,
        "lon": -52.944,
        "estado": "PR",
    },
    # ── INECOL / CANTAREIRA ────────────────────────────────────────────────
    {
        "nome": "PEDREIRA INECOL",
        "procedencias": ["INECOL", "CANTAREIRA"],
        "localizacao": "CAMPO LARGO - PR",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-277, S/N, KM 8,5, Campo Largo - PR",
        "lat": -25.459,
        "lon": -49.531,
        "estado": "PR",
    },
    # ── ITAIPU ─────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ITAIPU",
        "procedencias": ["PEDREIRA ITAIPU", "ITAIPU"],
        "localizacao": "SANTA HELENA / CAMPO MOURÃO - PR",
        "natureza": "BASALTO",
        "endereco": "Reservatório da UHE Itaipu, Santa Helena - PR",
        "lat": -24.870,
        "lon": -54.322,
        "estado": "PR",
    },
    # ── DRISNER ────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DRISNER",
        "procedencias": ["DRISNER"],
        "localizacao": "MARIPÁ - PR",
        "natureza": "BASALTO",
        "endereco": "Zona rural de Maripá - PR (polo agrícola oeste paranaense)",
        "lat": -24.420,
        "lon": -53.843,
        "estado": "PR",
    },
    # ── ARTECIPE ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ARTECIPE",
        "procedencias": ["ARTECIPE"],
        "localizacao": "QUITANDINHA - PR",
        "natureza": "GRANITO",
        "endereco": "Cinturão rural - Região Metropolitana de Curitiba, Quitandinha - PR",
        "lat": -25.872,
        "lon": -49.498,
        "estado": "PR",
    },
    # ── CASALI ─────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CASALI",
        "procedencias": ["CASALI"],
        "localizacao": "CAMPO MOURÃO - PR",
        "natureza": "BASALTO",
        "endereco": "Entroncamento viário central do Paraná, Campo Mourão - PR (BR-369)",
        "lat": -24.045,
        "lon": -52.379,
        "estado": "PR",
    },
    # ── CMIX ───────────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CMIX",
        "procedencias": ["CMIX", "PEDREIRA CMIX"],
        "localizacao": "TOLEDO - PR",
        "natureza": "BASALTO",
        "endereco": "Toledo - PR (consórcio CMIX + DALMINA, BR-163)",
        "lat": -24.721,
        "lon": -53.744,
        "estado": "PR",
    },
    # ── NORTE SUL ──────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA NORTE SUL",
        "procedencias": ["NORTE SUL"],
        "localizacao": "SÃO JOÃO DO IVAÍ / APUCARANA - PR",
        "natureza": "BASALTO",
        "endereco": "Vale do Ivaí - Apucarana - PR",
        "lat": -23.767,
        "lon": -51.579,
        "estado": "PR",
    },
    # ── CIANORTE ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CIANORTE",
        "procedencias": ["CIANORTE", "NOVO ITACOLOMI"],
        "localizacao": "CIANORTE / NOVO ITACOLOMI - PR",
        "natureza": "BASALTO",
        "endereco": "Noroeste paranaense, Cianorte - PR (IBGE SIRGAS 2000: Lat -23.82)",
        "lat": -23.661,
        "lon": -52.615,
        "estado": "PR",
    },
    # ── NOVA PICCINE ───────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA NOVA PICCINE",
        "procedencias": ["NOVA PICCINE", "PICCINE"],
        "localizacao": "ARAPONGAS - PR",
        "natureza": "BASALTO",
        "endereco": "Arabaldes do terceiro planalto, Arapongas - PR",
        "lat": -23.300,
        "lon": -51.420,
        "estado": "PR",
    },
    # ── CONPASUL ───────────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA CONPASUL",
        "procedencias": ["CONPASUL"],
        "localizacao": "BUTIÁ - RS",
        "natureza": "GRANITO",
        "endereco": "Escudo Sul-rio-grandense, Butiá - RS",
        "lat": -30.119,
        "lon": -51.964,
        "estado": "RS",
    },

    # ==========================================================================
    # BLOCO 2: ADIÇÕES 2026 — VALE DO ITAJAÍ / NORTE CATARINENSE / SC / PR
    # ==========================================================================

    # ── INFRASUL (endereço preciso) ─────────────────────────────────────────
    {
        "nome": "PEDREIRA INFRASUL - MINA RIO ZOADA",
        "procedencias": ["INFRASUL"],
        "localizacao": "JOINVILLE - SC",
        "natureza": "GNAISSE",
        "endereco": "Rodovia SC-108, s/n, KM 20, Bairro Vila Nova, Joinville - SC",
        "lat": -26.155,
        "lon": -48.822,
        "estado": "SC",
    },
    # ── MINERAÇÃO RIO DO OURO ─────────────────────────────────────────────────
    {
        "nome": "MINERAÇÃO RIO DO OURO - MINA OURINHOS",
        "procedencias": ["RIO DO OURO", "OURINHOS"],
        "localizacao": "BOTUVERÁ - SC",
        "natureza": "GRANITO",
        "endereco": "Rodovia SC-486, Estrada Geral, Bairro Lageado, Botuverá - SC",
        "lat": -27.210,
        "lon": -49.120,
        "estado": "SC",
    },
    # ── PEDREIRA VALE DO SELKE ────────────────────────────────────────────────
    {
        "nome": "PEDREIRA VALE DO SELKE (OURO PRETO MINERAÇÃO)",
        "procedencias": ["VALE DO SELKE", "OURO PRETO MINERAÇÃO"],
        "localizacao": "POMERODE - SC",
        "natureza": "GRANITO",
        "endereco": "Rua Vale do Selke Grande, 1180, Bairro Vale do Selke, Pomerode - SC",
        "lat": -26.745,
        "lon": -49.210,
        "estado": "SC",
    },
    # ── BRITAGEM FORTUNATO ────────────────────────────────────────────────────
    {
        "nome": "BRITAGEM FORTUNATO",
        "procedencias": ["FORTUNATO", "PEDREIRA FORTUNATO"],
        "localizacao": "GARUVA - SC",
        "natureza": "GRANITO",
        "endereco": "Rodovia SC-416, KM 8, Garuva - SC",
        "lat": -26.050,
        "lon": -48.830,
        "estado": "SC",
    },
    # ── BLUMETERRA MINERAÇÃO ──────────────────────────────────────────────────
    {
        "nome": "BLUMETERRA MINERAÇÃO",
        "procedencias": ["BLUMETERRA"],
        "localizacao": "RODEIO - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-470, Rodeio - SC",
        "lat": -26.826,
        "lon": -49.366,
        "estado": "SC",
    },
    # ── PEDREIRA GRABOWSKI ────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA GRABOWSKI",
        "procedencias": ["GRABOWSKI", "PEDREIRA GRABOWSKI"],
        "localizacao": "IBIRAMA - SC",
        "natureza": "BASALTO",
        "endereco": "Zona de extração, Ibirama - SC",
        "lat": -27.057,
        "lon": -49.519,
        "estado": "SC",
    },
    # ── RUDNICK MINÉRIOS ──────────────────────────────────────────────────────
    {
        "nome": "RUDNICK MINÉRIOS",
        "procedencias": ["RUDNICK"],
        "localizacao": "GARUVA - SC",
        "natureza": "GRANITO",
        "endereco": "Frente de lavra e beneficiamento, Garuva - SC",
        "lat": -26.027,
        "lon": -48.851,
        "estado": "SC",
    },
    # ── PEDREIRA HUBENER ──────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA HUBENER",
        "procedencias": ["HUBENER"],
        "localizacao": "JOINVILLE - SC",
        "natureza": "GRANITO",
        "endereco": "Britador e extração, Joinville - SC",
        "lat": -26.304,
        "lon": -48.846,
        "estado": "SC",
    },
    # ── PEDREIRA DO AUGUSTO ───────────────────────────────────────────────────
    {
        "nome": "PEDREIRA DO AUGUSTO",
        "procedencias": ["PEDREIRA DO AUGUSTO", "AUGUSTO"],
        "localizacao": "BRUSQUE - SC",
        "natureza": "MIGMATITO",
        "endereco": "Extração de migmatito e saibro, Brusque - SC",
        "lat": -27.097,
        "lon": -48.916,
        "estado": "SC",
    },
    # ── MINERAÇÃO JUNDU ───────────────────────────────────────────────────────
    {
        "nome": "MINERAÇÃO JUNDU - MINA FAZENDA DO JUCA",
        "procedencias": ["JUNDU"],
        "localizacao": "SÃO JOÃO DO ITAPERIÚ - SC",
        "natureza": "AREIA",
        "endereco": "Lavra de areia, São João do Itaperiú - SC",
        "lat": -26.637,
        "lon": -48.802,
        "estado": "SC",
    },
    # ── PEDRITA / PONTE RIO CUBÍCULO ──────────────────────────────────────────
    {
        "nome": "PEDRITA - PONTE RIO CUBÍCULO",
        "procedencias": ["PEDRITA"],
        "localizacao": "JAGUARUNA - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-101, KM 347, Jaguaruna - SC",
        "lat": -28.614,
        "lon": -48.998,
        "estado": "SC",
    },
    # ── SULCATARINENSE MINERAÇÃO ──────────────────────────────────────────────
    {
        "nome": "SULCATARINENSE MINERAÇÃO - SCHROEDER",
        "procedencias": ["SULCATARINENSE", "BRITASUL", "MINERADORA BRITASUL"],
        "localizacao": "SCHROEDER - SC",
        "natureza": "BASALTO",
        "endereco": "Margem da Rodovia BR-280, Schroeder - SC",
        "lat": -26.420,
        "lon": -48.982,
        "estado": "SC",
    },
    {
        "nome": "SULCATARINENSE MINERAÇÃO - BIGUAÇU",
        "procedencias": ["SULCATARINENSE BIGUAÇU"],
        "localizacao": "BIGUAÇU - SC",
        "natureza": "BASALTO",
        "endereco": "Rua Treze de Maio, 2.900, KM 03, Bairro Encruzilhada, Biguaçu - SC",
        "lat": -27.493,
        "lon": -48.655,
        "estado": "SC",
    },
    # ── RIO DO VALE MINERAÇÃO ─────────────────────────────────────────────────
    {
        "nome": "RIO DO VALE MINERAÇÃO",
        "procedencias": ["RIO DO VALE"],
        "localizacao": "ORLEANS - SC",
        "natureza": "BASALTO",
        "endereco": "Pátio de estocagem e frentes de lavra, Orleans - SC",
        "lat": -28.362,
        "lon": -49.295,
        "estado": "SC",
    },
    # ── MINÉRIOS AZAMBUJA ─────────────────────────────────────────────────────
    {
        "nome": "MINÉRIOS AZAMBUJA",
        "procedencias": ["AZAMBUJA"],
        "localizacao": "PEDRAS GRANDES - SC",
        "natureza": "BASALTO",
        "endereco": "Área de lavra, Pedras Grandes - SC",
        "lat": -28.438,
        "lon": -49.224,
        "estado": "SC",
    },
    # ── PEDREIRA JOAÇABA ─────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA JOAÇABA",
        "procedencias": ["JOAÇABA", "JOACABA", "PEDREIRA JOAÇABA"],
        "localizacao": "CAPINZAL - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia SC-303, KM 12, Bairro Engenho Novo, Capinzal - SC",
        "lat": -27.268,
        "lon": -51.560,
        "estado": "SC",
    },
    # ── PEDREIRA TRIÂNGULO ────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA TRIÂNGULO",
        "procedencias": ["TRIÂNGULO", "TRIANGULO", "PEDREIRA TRIÂNGULO"],
        "localizacao": "IBICARÉ - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia SC-453, KM 60, Linha Triângulo, Ibicaré - SC",
        "lat": -27.085,
        "lon": -51.325,
        "estado": "SC",
    },
    # ── BRITABAL ──────────────────────────────────────────────────────────────
    {
        "nome": "BRITABAL INDÚSTRIA E COMÉRCIO",
        "procedencias": ["BRITABAL", "PEDREIRA BRITABAL"],
        "localizacao": "CORDILHEIRA ALTA - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia Estadual 468, KM 3,5, Distrito Rural, Cordilheira Alta - SC",
        "lat": -27.120,
        "lon": -51.966,
        "estado": "SC",
    },
    # ── BRITAPAR ─────────────────────────────────────────────────────────────
    {
        "nome": "BRITAPAR",
        "procedencias": ["BRITAPAR", "PEDREIRA BRITAPAR"],
        "localizacao": "PAPANDUVA - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-116, KM 53, Papanduva - SC",
        "lat": -26.380,
        "lon": -50.130,
        "estado": "SC",
    },
    # ── GAIA RODOVIAS ─────────────────────────────────────────────────────────
    {
        "nome": "GAIA RODOVIAS",
        "procedencias": ["GAIA RODOVIAS", "GAIA"],
        "localizacao": "MARAVILHA - SC",
        "natureza": "BASALTO",
        "endereco": "Área de pedreira/extração, Maravilha - SC",
        "lat": -26.761,
        "lon": -53.174,
        "estado": "SC",
    },
    # ── SETEP / SBM — UNIDADES ADICIONAIS ────────────────────────────────────
    {
        "nome": "SETEP / SBM - URUSSANGA",
        "procedencias": ["SETEP URUSSANGA", "SBM URUSSANGA"],
        "localizacao": "URUSSANGA - SC",
        "natureza": "BASALTO",
        "endereco": "Estrada Geral, KM 08, Localidade Rio Maior, Urussanga - SC",
        "lat": -28.519,
        "lon": -49.323,
        "estado": "SC",
    },
    {
        "nome": "SETEP / SBM - VARGEM BONITA",
        "procedencias": ["SETEP VARGEM BONITA", "SBM VARGEM BONITA"],
        "localizacao": "VARGEM BONITA - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-153, KM 55, Bairro Campina Alegria, Vargem Bonita - SC",
        "lat": -27.001,
        "lon": -52.074,
        "estado": "SC",
    },
    {
        "nome": "SETEP / SBM - PAULO LOPES",
        "procedencias": ["SETEP PAULO LOPES", "SBM PAULO LOPES"],
        "localizacao": "PAULO LOPES - SC",
        "natureza": "GRANITO",
        "endereco": "Estrada Geral Sertão do Campo, s/n, Localidade Povo Novo, Paulo Lopes - SC",
        "lat": -27.894,
        "lon": -48.676,
        "estado": "SC",
    },
    {
        "nome": "SETEP / SBM - CAMPOS NOVOS",
        "procedencias": ["SETEP CAMPOS NOVOS", "SBM CAMPOS NOVOS"],
        "localizacao": "CAMPOS NOVOS - SC",
        "natureza": "BASALTO",
        "endereco": "Rodovia BR-470, KM 317, Fazenda Boa Vista, Campos Novos - SC",
        "lat": -27.399,
        "lon": -51.228,
        "estado": "SC",
    },
    # ── PEDREIRA ITAX (PR) ────────────────────────────────────────────────────
    {
        "nome": "PEDREIRA ITAX",
        "procedencias": ["ITAX", "PEDREIRA ITAX"],
        "localizacao": "GUARAPUAVA - PR",
        "natureza": "BASALTO",
        "endereco": "Margem da Rodovia PR-170, Guarapuava - PR",
        "lat": -25.436,
        "lon": -51.510,
        "estado": "PR",
    },
    # ── PEDREIRA REMANSO — FOZ DO IGUAÇU ─────────────────────────────────────
    {
        "nome": "PEDREIRA REMANSO - FOZ DO IGUAÇU",
        "procedencias": ["REMANSO FOZ", "REMANSO GRANDE"],
        "localizacao": "FOZ DO IGUAÇU - PR",
        "natureza": "BASALTO",
        "endereco": "Rua Astorga, s/n, Bairro Remanso Grande, Foz do Iguaçu - PR",
        "lat": -25.548,
        "lon": -54.589,
        "estado": "PR",
    },
]
